---
language: node_js
node_js:
  - "8"
sudo: required
env:
  - MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm config set spin false
install:
  - yarn install --non-interactive --no-lockfile
script:
  - yarn test
