---
language: node_js
node_js:
  - "8"
sudo: required
dist: trusty
addons:
  chrome: stable
  firefox: latest
cache:
  yarn: true
  directories:
    - $HOME/.cache
install:
  - yarn install --no-lockfile
script:
  - yarn test
